{% set name = "do-mpc" %}
{% set version = "4.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/do_mpc-{{ version }}.tar.gz
  sha256: a6a59fc6b26f7c1c0228f14f7ff178456e1f9943e6657999b41db46b243c1078

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - casadi
    - numpy
    - matplotlib-base
    - scipy
    - onnx
    - asyncua
    - packaging

test:
  imports:
    - do_mpc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.do-mpc.com
  summary: Model predictive control python toolbox
  description: |
    do-mpc is a comprehensive open-source toolbox for
    robust model predictive control (MPC) and moving horizon estimation (MHE)
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  doc_url: https://www.do-mpc.com
  dev_url: https://github.com/do-mpc/do-mpc

extra:
  recipe-maintainers:
    - beenje
